// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seller_Finance_Service.src._03_Infrastructure.Data;

#nullable disable

namespace Seller_Finance_Service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Seller_Finance_Service.src._01_Domain.Core.Entities.SellerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SellerAccounts", null, t =>
                        {
                            t.Property("CreatedAt")
                                .HasColumnName("SellerAccount_CreatedAt");
                        });
                });

            modelBuilder.Entity("Seller_Finance_Service.src._01_Domain.Core.Entities.SellerHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount_Value")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsReleased")
                        .HasColumnType("bit");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SellerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SellerHolds", null, t =>
                        {
                            t.Property("CreatedAt")
                                .HasColumnName("SellerHold_CreatedAt");
                        });
                });

            modelBuilder.Entity("Seller_Finance_Service.src._01_Domain.Core.Entities.SellerPayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount_Value")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GatewayReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SellerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SellerPayouts", null, t =>
                        {
                            t.Property("CreatedAt")
                                .HasColumnName("SellerPayout_CreatedAt");
                        });
                });

            modelBuilder.Entity("Seller_Finance_Service.src._01_Domain.Core.Entities.SellerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SellerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SellerTransactions", null, t =>
                        {
                            t.Property("CreatedAt")
                                .HasColumnName("SellerTransaction_CreatedAt");
                        });
                });

            modelBuilder.Entity("Seller_Finance_Service.src._01_Domain.Core.Entities.SellerAccount", b =>
                {
                    b.OwnsOne("Seller_Finance_Service.src._01_Domain.Core.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("SellerAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("LastModifiedAt");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("SellerAccountId");

                            b1.ToTable("SellerAccounts");

                            b1.WithOwner()
                                .HasForeignKey("SellerAccountId");
                        });

                    b.OwnsOne("Seller_Finance_Service.src._01_Domain.Core.Entities.SellerBalance", "Balance", b1 =>
                        {
                            b1.Property<Guid>("SellerAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("SellerAccountId");

                            b1.ToTable("SellerAccounts");

                            b1.WithOwner()
                                .HasForeignKey("SellerAccountId");

                            b1.OwnsOne("Seller_Finance_Service.src._01_Domain.Core.ValueObjects.Money", "AvailableBalance", b2 =>
                                {
                                    b2.Property<Guid>("SellerBalanceSellerAccountId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18)
                                        .HasColumnType("decimal(18,0)")
                                        .HasColumnName("AvailableBalanceAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("SellerBalanceSellerAccountId");

                                    b2.ToTable("SellerAccounts");

                                    b2.WithOwner()
                                        .HasForeignKey("SellerBalanceSellerAccountId");
                                });

                            b1.OwnsOne("Seller_Finance_Service.src._01_Domain.Core.ValueObjects.Money", "HoldBalance", b2 =>
                                {
                                    b2.Property<Guid>("SellerBalanceSellerAccountId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18)
                                        .HasColumnType("decimal(18,0)")
                                        .HasColumnName("HoldBalanceAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("SellerBalanceSellerAccountId");

                                    b2.ToTable("SellerAccounts");

                                    b2.WithOwner()
                                        .HasForeignKey("SellerBalanceSellerAccountId");
                                });

                            b1.OwnsOne("Seller_Finance_Service.src._01_Domain.Core.ValueObjects.Money", "PendingBalance", b2 =>
                                {
                                    b2.Property<Guid>("SellerBalanceSellerAccountId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18)
                                        .HasColumnType("decimal(18,0)")
                                        .HasColumnName("PendingBalanceAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("SellerBalanceSellerAccountId");

                                    b2.ToTable("SellerAccounts");

                                    b2.WithOwner()
                                        .HasForeignKey("SellerBalanceSellerAccountId");
                                });

                            b1.Navigation("AvailableBalance")
                                .IsRequired();

                            b1.Navigation("HoldBalance")
                                .IsRequired();

                            b1.Navigation("PendingBalance")
                                .IsRequired();
                        });

                    b.OwnsOne("Seller_Finance_Service.src._01_Domain.Core.ValueObjects.BankAccountInfo", "BankAccount", b1 =>
                        {
                            b1.Property<Guid>("SellerAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AccountHolderName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("AccountHolderName");

                            b1.Property<string>("AccountNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("BankAccountNumber");

                            b1.Property<string>("BankName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BankName");

                            b1.Property<string>("ShebaNumber")
                                .IsRequired()
                                .HasMaxLength(26)
                                .HasColumnType("nvarchar(26)")
                                .HasColumnName("ShebaNumber");

                            b1.HasKey("SellerAccountId");

                            b1.ToTable("SellerAccounts");

                            b1.WithOwner()
                                .HasForeignKey("SellerAccountId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("BankAccount")
                        .IsRequired();
                });

            modelBuilder.Entity("Seller_Finance_Service.src._01_Domain.Core.Entities.SellerHold", b =>
                {
                    b.OwnsOne("Seller_Finance_Service.src._01_Domain.Core.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("SellerHoldId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("LastModifiedAt");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("SellerHoldId");

                            b1.ToTable("SellerHolds");

                            b1.WithOwner()
                                .HasForeignKey("SellerHoldId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Seller_Finance_Service.src._01_Domain.Core.Entities.SellerPayout", b =>
                {
                    b.OwnsOne("Seller_Finance_Service.src._01_Domain.Core.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("SellerPayoutId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("LastModifiedAt");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("SellerPayoutId");

                            b1.ToTable("SellerPayouts");

                            b1.WithOwner()
                                .HasForeignKey("SellerPayoutId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Seller_Finance_Service.src._01_Domain.Core.Entities.SellerTransaction", b =>
                {
                    b.OwnsOne("Seller_Finance_Service.src._01_Domain.Core.ValueObjects.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("SellerTransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime?>("LastModifiedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("LastModifiedAt");

                            b1.Property<string>("LastModifiedBy")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastModifiedBy");

                            b1.HasKey("SellerTransactionId");

                            b1.ToTable("SellerTransactions");

                            b1.WithOwner()
                                .HasForeignKey("SellerTransactionId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
